import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import test from "node:test";

globalThis.HTMLElement = class {};
globalThis.customElements = {definitions:new Map(),get(name){return this.definitions.get(name);},define(name,value){this.definitions.set(name,value);}};
globalThis.window = {};
globalThis.CustomEvent = class {constructor(type,options){this.type=type;Object.assign(this,options);}};
const fakeElement=localName=>({localName,children:[],attributes:{},listeners:{},append(...children){this.children.push(...children);},setAttribute(name,value){this.attributes[name]=value;},addEventListener(name,listener){this.listeners[name]=listener;}});
globalThis.document = {createElement:fakeElement};
globalThis.fetch = async url => {
  const language=String(url).match(/\/([a-z]{2,3})\.json$/)?.[1]||"en";
  const catalog=JSON.parse(readFileSync(new URL(`../../custom_components/tasks/translations/${language}.json`,import.meta.url),"utf8"));
  return {ok:true,json:async()=>catalog};
};

const {ready,setLanguage}=await import("../../custom_components/tasks/frontend/localize.js");
await ready;
await setLanguage("en");
const {DEFAULT_CARD_CONFIG,TasksCardEditor,UNASSIGNED,canEditCard,dashboardCardBodyHtml,dashboardTaskRowHtml,dueStatus,filterDashboardTasks,normalizeCardConfig,sortDashboardTasks}=await import("../../custom_components/tasks/frontend/dashboard-card.js");
const {TasksBase,TasksPanel}=await import("../../custom_components/tasks/frontend/controller.js");
const {EDITOR_FILE_GRID}=await import("../../custom_components/tasks/frontend/popup-task-editor.js");
const {TASK_VIEWER_TAG,showTaskViewer}=await import("../../custom_components/tasks/frontend/popup-task-viewer.js");
const {ATTACHMENT_VIEWER_TAG,attachmentPreviewHtml,showAttachmentViewer}=await import("../../custom_components/tasks/frontend/popup-attachment-viewer.js");
const {TASK_EDITOR_TAG,taskEditorFooterHtml,showTaskEditorPopup}=await import("../../custom_components/tasks/frontend/popup-task-editor.js");
const {CONFIRM_POPUP_TAG,showConfirmation}=await import("../../custom_components/tasks/frontend/popup-confirm.js");
const {createActionMenu}=await import("../../custom_components/tasks/frontend/action-menu.js");
const {taskDetailBoxHtml,taskFilesBoxHtml,taskHistoryBoxHtml}=await import("../../custom_components/tasks/frontend/popup-task-editor.js");

const tasks=[
  {task_id:"old",task_name:"Mopping",task_due:"2026-07-20",assignee_id:"alice"},
  {task_id:"today",task_name:"Dishes",task_due:"2026-07-21",assignee_id:null},
  {task_id:"soon",task_name:"Bad",task_due:"2026-07-24",assignee_id:"bob"},
  {task_id:"later",task_name:"Windows",task_due:"2026-08-01",assignee_id:null},
];

test("default config shows overdue and today",()=>assert.deepEqual(filterDashboardTasks(tasks,DEFAULT_CARD_CONFIG,"2026-07-21").map(task=>task.task_id),["old","today"]));
test("due day window includes its future boundary",()=>assert.deepEqual(filterDashboardTasks(tasks,{due_days:3},"2026-07-21").map(task=>task.task_id),["old","today","soon"]));
test("null due day window includes every due date",()=>assert.equal(filterDashboardTasks(tasks,{due_days:null},"2026-07-21").length,4));
test("assignee filter supports multiple selections",()=>assert.deepEqual(filterDashboardTasks(tasks,{due_days:null,assignee_ids:["alice",UNASSIGNED]},"2026-07-21").map(task=>task.task_id),["old","today","later"]));

test("sorting always puts the oldest tasks first with a name tiebreaker without mutation",()=>{const input=[{task_id:"b",task_name:"Zulu",task_due:"2026-07-21"},{task_id:"a",task_name:"Alpha",task_due:"2026-07-21"},{task_id:"c",task_name:"Later",task_due:"2026-07-22"}],original=[...input];assert.deepEqual(sortDashboardTasks(input).map(task=>task.task_id),["a","b","c"]);assert.deepEqual(input,original);});
test("normalization preserves null, sanitizes invalid values, and removes unsupported options",()=>{assert.equal(normalizeCardConfig({due_days:null}).due_days,null);assert.equal(normalizeCardConfig({due_days:-2,mode:"other"}).due_days,0);assert.equal(normalizeCardConfig({mode:"other"}).mode,"view");assert.equal(normalizeCardConfig({sort_direction:"desc",hide_card_background:true}).sort_direction,undefined);assert.equal(normalizeCardConfig({hide_card_background:true}).hide_card_background,undefined);});

test("due status separates overdue, today, and future dates",()=>{assert.equal(dueStatus("2026-07-20","2026-07-21"),"overdue");assert.equal(dueStatus("2026-07-21","2026-07-21"),"today");assert.equal(dueStatus("2026-07-22","2026-07-21"),"future");});
test("dashboard tasks use neutral Home Assistant tile surfaces",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/dashboard-card.js",import.meta.url),"utf8");assert.match(source,/background:var\(--ha-card-background,var\(--card-background-color\)\)/);assert.match(source,/border:1px solid var\(--ha-card-border-color,var\(--divider-color\)\)/);assert.doesNotMatch(source,/background:color-mix\(in srgb,var\(--task-color/);assert.match(source,/\.due-date\.overdue\{--primary-text-color:var\(--error-color/);});
test("view rows show outlined native due, assignee, and NFC chips without actions",()=>{const html=dashboardTaskRowHtml(tasks[0],false,"yesterday","overdue","Alice","Laundry tag");assert.doesNotMatch(html,/dots-vertical|row-action-toggle|house|<ha-assist-chip filled/);assert.match(html,/Mopping/);assert.match(html,/<ha-chip-set>/);assert.match(html,/<ha-assist-chip class="due-date overdue" label="yesterday"/);assert.match(html,/slot="icon" icon="mdi:account"[\s\S]*label="Alice"|label="Alice"[\s\S]*slot="icon" icon="mdi:account"/);assert.match(html,/label="Laundry tag"[\s\S]*slot="icon" icon="mdi:nfc"/);});
test("dashboard uses native chips while due chips retain status colors",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/dashboard-card.js",import.meta.url),"utf8");assert.match(source,/this\.themeStyles\(\)/);assert.doesNotMatch(source,/pillStyles|taskSurfaceStyles|class="pill/);assert.match(source,/\.due-date\.today\{--primary-text-color:var\(--warning-color/);assert.match(source,/\.due-date\.overdue\{--primary-text-color:var\(--error-color/);assert.match(source,/\.due-date\.future\{--primary-text-color:var\(--success-color/);});
test("dashboard delegates outlined metadata chips and panel rows to Home Assistant",()=>{const dashboard=readFileSync(new URL("../../custom_components/tasks/frontend/dashboard-card.js",import.meta.url),"utf8"),list=readFileSync(new URL("../../custom_components/tasks/frontend/sidebar-task-list.js",import.meta.url),"utf8");assert.match(dashboard,/<ha-chip-set>/);assert.match(dashboard,/<ha-assist-chip/);assert.doesNotMatch(dashboard,/<ha-assist-chip filled/);assert.match(list,/hass-tabs-subpage-data-table/);assert.doesNotMatch(list,/pillStyles\(\)|taskRow\(/);assert.doesNotMatch(dashboard,/pillIconCss\(\)/);});
test("edit rows reserve a native action-menu slot",()=>{const html=dashboardTaskRowHtml(tasks[0],true,"yesterday","overdue");assert.match(html,/class="row-action-slot"/);assert.doesNotMatch(html,/row-action-menu|style=/);});
test("shared action menu uses native HA dropdown controls and dispatches actions",()=>{let edited=0,removed=0,stopped=0;const menu=createActionMenu({label:"Task actions",edit:()=>edited++,remove:()=>removed++});assert.equal(menu.localName,"ha-dropdown");assert.deepEqual(menu.children.map(child=>child.localName),["ha-icon-button","ha-dropdown-item","ha-dropdown-item"]);assert.equal(menu.children[0].attributes["aria-label"],"Task actions");assert.equal(menu.children[2].attributes.variant,"danger");menu.listeners.pointerdown({stopPropagation:()=>stopped++});menu.listeners.click({stopPropagation:()=>stopped++});menu.listeners["wa-select"]({stopPropagation:()=>stopped++,detail:{item:{value:"edit"}}});menu.listeners["wa-select"]({stopPropagation:()=>stopped++,detail:{item:{value:"delete"}}});assert.equal(edited,1);assert.equal(removed,1);assert.equal(stopped,4);});
test("edit mode is controlled only by card configuration",()=>{assert.equal(canEditCard({mode:"edit"}),true);assert.equal(canEditCard({mode:"view"}),false);});

test("editor update emits a dashboard-local config change",()=>{const editor=Object.create(TasksCardEditor.prototype);editor.config={...DEFAULT_CARD_CONFIG};editor.render=()=>{};let event;editor.dispatchEvent=value=>{event=value;};editor.update({mode:"edit",assignee_ids:["alice"]});assert.equal(event.type,"config-changed");assert.equal(event.detail.config.mode,"edit");assert.deepEqual(event.detail.config.assignee_ids,["alice"]);});
test("repeated hass updates do not rerender and steal editor focus",()=>{const editor=Object.create(TasksCardEditor.prototype);editor.loaded=true;let renders=0;editor.render=()=>{renders++;};Object.getOwnPropertyDescriptor(TasksCardEditor.prototype,"hass").set.call(editor,{user:{}});assert.equal(renders,0);});
test("shared controller reloads from Tasks events",async()=>{const controller=Object.create(TasksBase.prototype);controller.eventUnsubscribe=null;controller.eventSubscriptionToken=0;let listener,eventType,loads=0;controller._hass={connection:{subscribeEvents:async(callback,type)=>{listener=callback;eventType=type;return()=>{};}}};controller.load=async()=>{loads++;};await controller.subscribeEvents();assert.equal(eventType,"tasks_event");await listener({data:{action:"updated",resource_type:"task"}});assert.equal(loads,1);});
test("shared controller removes stale event subscriptions",async()=>{const controller=Object.create(TasksBase.prototype);controller.eventUnsubscribe=null;controller.eventSubscriptionToken=0;let removed=0;controller._hass={connection:{subscribeEvents:async()=>()=>{removed++;}}};await controller.subscribeEvents();controller.unsubscribeEvents();assert.equal(removed,1);assert.equal(controller.eventUnsubscribe,null);});
test("ordinary hass updates no longer reload task data",async()=>{const controller=Object.create(TasksBase.prototype),descriptor=Object.getOwnPropertyDescriptor(TasksBase.prototype,"hass"),settle=()=>new Promise(resolve=>setImmediate(resolve));controller.loaded=true;controller.eventUnsubscribe=()=>{};controller.eventSubscriptionToken=0;let loads=0,renders=0;controller.load=async()=>{loads++;};controller.render=()=>{renders++;};const connection={subscribeEvents:async()=>()=>{}};descriptor.set.call(controller,{connection,locale:{language:"en"},states:{"todo.tasks":{state:"1"}}});await settle();descriptor.set.call(controller,{connection,locale:{language:"en"},states:{"todo.tasks":{state:"0"}}});await settle();assert.equal(loads,0);assert.equal(renders,0);});
test("concurrent loads are coalesced into one pending reload",async()=>{const controller=Object.create(TasksBase.prototype);controller._hass={};controller.loading=true;controller.reloadPending=false;await controller.load();await controller.load();assert.equal(controller.reloadPending,true);});
test("panel uses an unregistered shared base instead of becoming the card base",async()=>{const {TasksCard}=await import("../../custom_components/tasks/frontend/dashboard-card.js");assert.equal(Object.getPrototypeOf(TasksPanel),TasksBase);assert.equal(Object.getPrototypeOf(TasksCard),TasksBase);assert.notEqual(Object.getPrototypeOf(TasksCard),TasksPanel);});
test("task viewer opens through Home Assistant's native show-dialog contract",()=>{let event;const controller={dispatchEvent:value=>{event=value;}};showTaskViewer(controller,tasks[0]);assert.equal(event.type,"show-dialog");assert.equal(event.bubbles,true);assert.equal(event.composed,true);assert.equal(event.detail.dialogTag,TASK_VIEWER_TAG);assert.equal(event.detail.dialogParams.task,tasks[0]);});
test("task viewer delegates descriptions directly to native Home Assistant markdown",()=>{const viewer=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-viewer.js",import.meta.url),"utf8");assert.match(viewer,/<ha-markdown breaks><\/ha-markdown>/);assert.match(viewer,/markdown\.content=task\.task_description/);assert.doesNotMatch(viewer,/ha-faded|content-resize|faded-content|markdown\(task\.description\)|markdownInline|export const markdown/);});
test("task viewer keeps only files and history in native expansion panels",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-viewer.js",import.meta.url),"utf8");assert.match(source,/controller\.typographyStyles\(\)/);assert.match(source,/<p class="recurrence ht-content">/);assert.match(source,/<textarea class="completion-notes ht-content"/);assert.match(source,/\$\{taskFilesBoxHtml\(controller,task\)\}\$\{taskHistoryBoxHtml\(controller,null\)\}/);assert.match(source,/<ha-expansion-panel outlined/);assert.doesNotMatch(source,/task\.planning|task\.description|task\.completion_notes[^"]*\),notes|<details|<summary/);});
test("task detail box helper delegates header typography and outlines to Home Assistant",()=>{assert.match(taskDetailBoxHtml("Name","Task",{expanded:true}),/^<ha-expansion-panel outlined expanded>/);assert.match(taskDetailBoxHtml("Files","None",{className:"files-box"}),/^<ha-expansion-panel outlined class="files-box">/);assert.doesNotMatch(taskDetailBoxHtml("Name","Task"),/slot="header" class=/);});
test("completion confirmation is owned by the task popup",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-viewer.js",import.meta.url),"utf8");assert.match(source,/class TasksPopupCompletionConfirm/);assert.match(source,/confirmCompletion\(this,this\.task\)/);assert.doesNotMatch(source,/native-form-dialog|controller\.confirmAction/);});
test("completion confirmation uses an existing translated action label",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-viewer.js",import.meta.url),"utf8");assert.match(source,/class="confirm"[\s\S]*?t\("task\.completed"\)/);assert.doesNotMatch(source,/t\("task\.complete"\)/);});
test("completion notes reuse the editor textarea formatting at their current viewer position",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-viewer.js",import.meta.url),"utf8");assert.match(source,/\.value\|\|""\)\.trim\(\)\|\|null/);assert.match(source,/<textarea class="completion-notes ht-content" style="resize:vertical" aria-label=/);assert.match(source,/controller\.formStyles\(\)/);assert.doesNotMatch(source,/\.completion-notes\{/);assert.match(source,/\$\{description\}\$\{notes\}\$\{taskFilesBoxHtml/);assert.doesNotMatch(source,/<ha-textarea|<wa-textarea/);});
test("task viewer places outlined chips first and keeps due in the first chip",()=>{const viewer=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-viewer.js",import.meta.url),"utf8"),main=readFileSync(new URL("../../custom_components/tasks/frontend/controller.js",import.meta.url),"utf8");assert.match(viewer,/due=task\.task_due\?`<ha-assist-chip label="\$\{esc\(controller\.date\(task\.task_due\)\)\}"><ha-icon slot="icon" icon="mdi:calendar"/);assert.match(viewer,/<div class="content"><ha-chip-set>\$\{due\}<ha-assist-chip label="\$\{esc\(assignee[\s\S]*?<\/ha-chip-set><p class="recurrence ht-content">/);assert.doesNotMatch(viewer,/<ha-assist-chip filled|chip\.filled/);assert.doesNotMatch(main,/next=task\.task_due|t\("task\.due"\).*this\.date/);});
test("task viewer appends NFC, file count, and labels in that order",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-viewer.js",import.meta.url),"utf8");const nfc=source.indexOf("icon=\"mdi:nfc\""),files=source.indexOf("icon=\"mdi:file-outline\""),labels=source.indexOf("icon=\"mdi:label-outline\"");assert.ok(nfc>0);assert.ok(files>nfc);assert.ok(labels>files);assert.match(source,/fileCount=this\.controller\.attachments\.filter\(file=>file\.task_id===this\.task\.task_id\)\.length/);assert.match(source,/files\.label=String\(fileCount\)/);});
test("task viewer appends labels and the assigned tag as outlined native chips",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-viewer.js",import.meta.url),"utf8");assert.match(source,/this\.render\(\);[\s\S]*?this\.addAssignmentChips\(\);this\.loadHistory\(\)/);assert.match(source,/createElement\("ha-assist-chip"\)/);assert.doesNotMatch(source,/chip\.filled=true/);assert.match(source,/slot="icon" icon="mdi:label-outline"/);assert.match(source,/slot="icon" icon="mdi:nfc"/);assert.match(source,/controller\.labelNames\(this\.task\)/);assert.match(source,/controller\.tagName\(this\.task\)/);assert.doesNotMatch(source,/pill/i);});
test("task viewer omits labels deleted from Home Assistant",()=>{const controller=Object.create(TasksBase.prototype);controller.labels=[{label_id:"known",name:"Known"}];assert.deepEqual(controller.labelNames({label_ids:["known","deleted"]}),["Known"]);});
test("task viewer omits NFC tags deleted from Home Assistant",()=>{const controller=Object.create(TasksBase.prototype);controller.tags=[{id:"known",name:"Known"}];assert.equal(controller.tagName({nfc_tag_id:"known"}),"Known");assert.equal(controller.tagName({nfc_tag_id:"deleted"}),"");});
test("task editor loads only existing Home Assistant users and tags into selects",()=>{const main=readFileSync(new URL("../../custom_components/tasks/frontend/controller.js",import.meta.url),"utf8"),editor=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.match(main,/this\.ws\(\{type:"tag\/list"\}\)/);assert.match(main,/this\.tags=Array\.isArray\(tags\)\?tags:\[\]/);assert.match(editor,/assigneeId=knownReferenceId\(t\.assignee_id,this\.users\)\|\|""/);assert.match(editor,/nfcTagId=knownReferenceId\(t\.nfc_tag_id,this\.tags\)\|\|""/);assert.match(editor,/tagOptions=\[\.\.\.this\.tags\]/);assert.match(editor,/\["assignee_id",tr\("task\.user"\),assigneeId/);assert.match(editor,/\["nfc_tag_id",tr\("task\.nfc_tag_id"\),nfcTagId/);assert.match(editor,/tr\("task\.no_nfc_tag"\)/);assert.doesNotMatch(editor,/tagOptions\.push/);});
test("task editor places the native multiple-label selector in Assignment",()=>{const main=readFileSync(new URL("../../custom_components/tasks/frontend/controller.js",import.meta.url),"utf8"),editor=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.match(main,/this\.ws\(\{type:"config\/label_registry\/list"\}\)/);assert.match(editor,/<label data-field="\$\{key\}">\$\{caption\}<input[^>]+><ha-selector><\/ha-selector><\/label>/);assert.match(editor,/\["label_ids",tr\("task\.labels"\)[\s\S]*?"labels"/);assert.match(editor,/labelIds=knownLabelIds\(JSON\.parse\(labelInput\.value\|\|"\[\]"\),this\.labels\)/);assert.match(editor,/labelInput\.value=JSON\.stringify\(labelIds\)/);assert.match(editor,/selector\.key="label_ids"/);assert.doesNotMatch(editor,/selector\.label=/);assert.match(editor,/selector\.selector=\{label:\{multiple:true\}\}/);assert.doesNotMatch(editor,/selector\.selector=\{select:/);assert.match(editor,/selector\.value=labelIds/);assert.match(editor,/JSON\.stringify\(event\.detail\?\.value\|\|\[\]\)/);assert.match(editor,/fields=\[form\.querySelector\('\[data-field="assignee_id"\]'\),labelField,form\.querySelector\('\[data-field="nfc_tag_id"\]'\)\]/);assert.match(editor,/labelField[\s\S]*fields\.forEach\(field=>content\.append\(field\)\)/);assert.match(editor,/label_ids:JSON\.parse/);});
test("editor fields assign typography classes by role",()=>{const controller=Object.create(TasksBase.prototype);assert.match(controller.field(["name","Name","",true]),/class="ht-label-medium"[\s\S]*class="ht-content"/);assert.match(controller.field(["schedule_type","Calculate due date","fixed",true,"select",[["fixed","Calendar"]]]),/class="ht-label-normal"[\s\S]*class="ht-content"/);assert.match(controller.field(["manufacturer","Manufacturer",""]),/class="ht-label-medium"[\s\S]*class="ht-content"/);});
test("editor keeps name and optional description as placeholders above the expandable sections",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.match(source,/createElement\("ha-expansion-panel"\)/);assert.match(source,/panel\.outlined=true/);assert.match(source,/panel\.expanded=expanded/);assert.match(source,/\["task_name",tr\("task\.name"\)/);assert.match(source,/\["task_description",tr\("task\.optional_description"\)/);assert.match(source,/\[\[name,tr\("task\.name"\)\],\[description,tr\("task\.optional_description"\)\]\]/);assert.match(source,/displayPlaceholder=`\$\{placeholder\}\$\{control\.required\?" \*":""\}`/);assert.match(source,/control\.placeholder=displayPlaceholder/);assert.match(source,/field\.querySelector\(":scope > span"\)\?\.remove\(\)/);assert.match(source,/form\.prepend\(name,description\)/);assert.doesNotMatch(source,/name-box|description-box/);assert.match(source,/header\.slot="header"/);assert.doesNotMatch(source,/prepareDetails|details-toggle|MutationObserver/);});
test("editors and confirmations use registered native dialog contracts",()=>{const events=[],controller={dispatchEvent:event=>events.push(event)};showTaskEditorPopup(controller,{title:"Editor",fields:[]});showConfirmation(controller,{title:"Delete",message:"Sure?",confirmLabel:"Delete"});assert.equal(events[0].detail.dialogTag,TASK_EDITOR_TAG);assert.equal(events[1].detail.dialogTag,CONFIRM_POPUP_TAG);assert.ok(events.every(event=>event.bubbles&&event.composed));});
test("native form dialogs no longer post-process collapsible sections",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.match(source,/controller\.typographyStyles\(\)/);assert.doesNotMatch(source,/dialogLayoutStyles|prepareDetails|details-toggle/);});
test("native editor actions use the same adaptive-dialog footer as the viewer",()=>{const html=taskEditorFooterHtml();assert.match(html,/ha-dialog-footer slot="footer"/);assert.match(html,/ha-button class="save" slot="primaryAction" variant="brand"/);assert.doesNotMatch(html,/<button/);});
test("native form source renders its footer directly without a legacy inline save action",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.doesNotMatch(source,/mountFooter|inlineSave|class="actions"|class="primary"/);assert.match(source,/\$\{taskEditorFooterHtml\(\)\}<\/ha-adaptive-dialog>/);});
test("frontend shells no longer contain legacy dialog placeholders",()=>{for(const file of ["controller.js","sidebar-task-list.js","dashboard-card.js"]){const source=readFileSync(new URL(`../../custom_components/tasks/frontend/${file}`,import.meta.url),"utf8");assert.doesNotMatch(source,/class="dialogs"|class="overlay"|modal-header|modal-close/);}});
test("attachment rows use the full filename in the flexible first column",()=>{const controller=Object.create(TasksBase.prototype);controller.signedFiles=new Map([["file","/signed/file"]]);const html=controller.fileLink({attachment_id:"file",filename:"a very long filename.pdf"});assert.match(html,/<a class="filename file-open" data-file-open="file" href="\/signed\/file"[^>]*>a very long filename\.pdf<\/a>/);assert.match(html,/overflow-wrap:anywhere/);assert.doesNotMatch(html,/filename-base|filename-extension|text-overflow|target="_blank"|<button/);assert.equal(EDITOR_FILE_GRID,"display:grid;grid-template-columns:minmax(0,1fr) max-content 32px;gap:8px;align-items:center;min-height:40px");});
test("signed attachment URLs are loaded only when a task popup opens",async()=>{const controller=Object.create(TasksBase.prototype),messages=[];controller.signedFiles=new Map();controller.ws=async message=>{messages.push(message);return {signed_files:{file:"/signed/file"}};};await controller.ensureTaskFileUrls("task");assert.deepEqual(messages,[{type:"tasks/attachment/urls",task_id:"task"}]);assert.equal(controller.signedFiles.get("file"),"/signed/file");const main=readFileSync(new URL("../../custom_components/tasks/frontend/controller.js",import.meta.url),"utf8"),editor=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.doesNotMatch(main,/d\.signed_files/);assert.match(main,/async taskViewer\(task\)\{try\{await this\.ensureTaskFileUrls\(task\.task_id\)/);assert.match(editor,/async taskEditor\(task=null\)\{if\(task\)try\{await this\.ensureTaskFileUrls\(task\.task_id\)/);});
test("viewer and editor file rows share a 40px height with compact delete actions",()=>{const controller={attachments:[{attachment_id:"file",task_id:"task",size:1024}],fileLink:()=>"<a>filename.pdf</a>",size:()=>"1 KB"},task={task_id:"task"};const viewer=taskFilesBoxHtml(controller,task),editor=taskFilesBoxHtml(controller,task,{editable:true});assert.match(viewer,/grid-template-columns:minmax\(0,1fr\) max-content[^>]+min-height:40px/);assert.match(editor,/grid-template-columns:minmax\(0,1fr\) max-content 32px[^>]+min-height:40px/);assert.doesNotMatch(editor,/padding:4px 0/);assert.match(editor,/--ha-icon-button-size:32px/);assert.match(editor,/mdi:delete/);assert.match(viewer,/class="file-size" style="justify-self:end;white-space:nowrap"/);});
test("popup expansion panels suppress Home Assistant's click fill via its own variable",()=>{for(const file of ["popup-task-viewer.js","popup-task-editor.js","popup-settings.js"]){const source=readFileSync(new URL(`../../custom_components/tasks/frontend/${file}`,import.meta.url),"utf8");assert.match(source,/ha-expansion-panel\{--input-fill-color:transparent\}/);}});
test("editable files use Home Assistant's native multiple file upload component",()=>{const controller={attachments:[],fileLink:()=>"",size:()=>""},html=taskFilesBoxHtml(controller,{task_id:"task"},{editable:true});assert.match(html,/<ha-selector class="file-upload-loader" hidden><\/ha-selector><ha-file-upload class="attachment-upload"><\/ha-file-upload>/);assert.doesNotMatch(html,/<input type="file"|attachment-drop-zone|choose-files/);const editor=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8"),main=readFileSync(new URL("../../custom_components/tasks/frontend/controller.js",import.meta.url),"utf8");assert.match(editor,/loader\.selector=\{file:\{accept:"\*\/\*"\}\}/);assert.match(editor,/upload\.multiple=true/);assert.match(editor,/upload\.addEventListener\("file-picked"/);assert.match(editor,/editor\.stagedFiles\.push/);assert.match(editor,/while\(editor\.stagedFiles\.length\)/);assert.match(editor,/this\.uploadNativeFile\(file\)/);assert.match(editor,/this\.attachUploadedFile\(editor\.task\.task_id,fileId\)/);assert.doesNotMatch(editor,/dropZone\.ondrop|dataTransfer\.files/);assert.match(main,/fetchWithAuth\("\/api\/file_upload"/);assert.match(main,/type:"tasks\/attachment\/create"/);assert.doesNotMatch(main,/\/api\/tasks\/upload/);});
test("new task editor stages files before creating their attachment records",()=>{const controller={attachments:[],fileLink:()=>"",size:value=>`${value} B`},html=taskFilesBoxHtml(controller,null,{editable:true,staged:[{name:"draft.txt",size:5}]});assert.match(html,/data-staged="0"/);assert.match(html,/>draft\.txt<\/span>/);assert.match(html,/>5 B<\/span>/);const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.match(source,/this\.mountDetails\(modal,editor,pendingFiles,pendingHistory\)/);assert.match(source,/const wasNew=!editor\.task;editor\.task=await this\.ws/);assert.match(source,/if\(wasNew\)createdInEditor=true/);assert.match(source,/if\(createdInEditor&&editor\.task\)\{try\{await this\.ws\(\{type:"tasks\/task\/delete"/);});
test("viewer and editor history rows share a 40px height with compact delete actions",()=>{const controller=Object.create(TasksBase.prototype);controller.locale=()=>"en";controller.historyTime=()=>"12:00";controller.date=value=>value;const viewer=controller.historyRow({history_entry_id:"entry",completion_date:"2026-07-22",user_name:"User"}),editor=controller.historyRow({history_entry_id:"entry",completion_date:"2026-07-22",user_name:"User"},true);for(const html of [viewer,editor]){assert.match(html,/align-items:center;min-height:40px;padding:0/);}assert.match(editor,/grid-template-columns:[^>]+ 32px/);assert.match(editor,/--ha-icon-button-size:32px/);assert.match(editor,/mdi:delete/);});
test("shared file and history boxes expose destructive controls only in editor mode",()=>{const controller={attachments:[{attachment_id:"file",task_id:"task",filename:"file.txt",size:4}],fileLink:()=>"<a>file</a>",size:()=>"4 B",historyRow:(_entry,editable)=>`<span>${editable}</span>`},task={task_id:"task"};assert.doesNotMatch(taskFilesBoxHtml(controller,task),/class="editor-action/);assert.match(taskFilesBoxHtml(controller,task,{editable:true}),/class="editor-action remove danger"/);assert.doesNotMatch(taskHistoryBoxHtml(controller,[{history_entry_id:"history"}]),/>true</);assert.match(taskHistoryBoxHtml(controller,[{history_entry_id:"history"}],{editable:true}),/>true</);});
test("planning schedule_interval uses an equal-height theme-aware stepper",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.match(source,/mountIntervalStepper\(field\)/);assert.match(source,/schedule-select,.schedule_interval-stepper\{[^}]*height:44px/);assert.match(source,/task\.interval_decrease/);assert.match(source,/task\.interval_increase/);assert.match(source,/ha-color-fill-neutral-quiet-hover/);assert.match(source,/event\.key==="ArrowUp"/);assert.match(source,/event\.key==="ArrowDown"/);});
test("optional start date supports direct iOS input and the desktop picker API",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.match(source,/startTrigger=document\.createElement\("label"\)/);assert.match(source,/startInput\.style\.cssText="position:absolute;inset:0;width:100%;height:100%/);assert.match(source,/startTrigger\.append\(startText,startInput\)/);assert.match(source,/startInput\.addEventListener\("click",\(\)=>\{try\{startInput\.showPicker\?\.\(\)/);assert.doesNotMatch(source,/startInput\.click\(\)/);});
test("optional start date exposes only the native picker action",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.match(source,/startBox\.querySelector\("\.start-date-actions"\)\.append\(startTrigger\)/);assert.doesNotMatch(source,/append\(startTrigger,startClear\)/);});
test("planning keeps the loaded due preview visible during recalculation",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.match(source,/if\(!summary\.dataset\.ready\)\{summary\.innerHTML=/);assert.match(source,/summary\.dataset\.ready="true"/);assert.match(source,/summary\.setAttribute\("aria-busy","true"\)/);assert.match(source,/request===previewRequest/);});
test("planning loads the full due preview once and expands it locally",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.match(source,/previewDates=result\.task_dues/);assert.match(source,/previewDates\.slice\(0,visibleCount\)/);assert.match(source,/more\.onclick=\(\)=>\{visibleCount=Math\.min\(visibleCount\+1,previewDates\.length\);renderSummary\(\);\}/);assert.doesNotMatch(source,/preview_next_due",\.\.\.task,count:/);});
test("attachments open through a native popup with media previews and download fallback",()=>{let event;const dispatcher={dispatchEvent:value=>{event=value;}};const file={attachment_id:"file",filename:"photo.jpg",content_type:"image/jpeg"};showAttachmentViewer(dispatcher,file,"/signed/file");assert.equal(event.type,"show-dialog");assert.equal(event.detail.dialogTag,ATTACHMENT_VIEWER_TAG);assert.equal(event.detail.dialogParams.file,file);assert.match(attachmentPreviewHtml(file,"/signed/file"),/<img /);assert.match(attachmentPreviewHtml({...file,content_type:"video/mp4"},"/signed/file"),/<video /);assert.match(attachmentPreviewHtml({...file,content_type:"audio/mpeg"},"/signed/file"),/<audio /);assert.match(attachmentPreviewHtml({...file,content_type:"application\/pdf"},"/signed/file"),/<iframe /);const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-attachment-viewer.js",import.meta.url),"utf8");assert.match(source,/ha-adaptive-dialog/);assert.match(source,/attachment\.download/);});
test("task editor popup does not expose delete actions",()=>{assert.equal(typeof TasksBase.prototype.mountTaskActions,"undefined");});
test("dashboard add action looks like a centered stronger dashed task row",()=>{const html=dashboardCardBodyHtml('<div class="task-row"></div>',true);assert.ok(html.indexOf("add-task")<html.indexOf("task-row"));assert.match(html,/<button class="add-task" type="button">\+ Add task<\/button>/);assert.doesNotMatch(html,/mdi:plus/);const source=readFileSync(new URL("../../custom_components/tasks/frontend/dashboard-card.js",import.meta.url),"utf8");assert.match(source,/\.add-task\{display:flex;align-items:center;justify-content:center;box-sizing:border-box;width:100%;min-height:52px/);assert.match(source,/border:2px dashed var\(--divider-color\)/);assert.match(source,/background:transparent;color:var\(--secondary-text-color\)/);assert.match(source,/text-align:center/);assert.match(source,/add\.onclick=\(\)=>\{add\.blur\(\);this\.taskEditor\(null\);\}/);assert.doesNotMatch(source,/\.add-task::part|card-actions/);});

test("dashboard renders all metadata as native chips while due colors remain explicit",()=>{const html=dashboardTaskRowHtml(tasks[0],false,"Today","today","Alex","Tag");assert.equal((html.match(/<ha-assist-chip /g)||[]).length,3);const source=readFileSync(new URL("../../custom_components/tasks/frontend/dashboard-card.js",import.meta.url),"utf8");assert.match(source,/ha-chip-set\{display:flex;gap:8px/);assert.match(source,/\.due-date\.today\{--primary-text-color:var\(--warning-color/);assert.match(source,/\.due-date\.overdue\{--primary-text-color:var\(--error-color/);assert.match(source,/\.due-date\.future\{--primary-text-color:var\(--success-color/);});
test("dashboard card is always frameless and its contents use the full width",()=>{const html=dashboardCardBodyHtml("",false);assert.match(html,/--ha-card-border-width:0px/);assert.match(html,/--ha-card-border-color:transparent/);assert.match(html,/border:none!important;background:transparent!important;box-shadow:none!important/);const source=readFileSync(new URL("../../custom_components/tasks/frontend/dashboard-card.js",import.meta.url),"utf8");assert.match(source,/\.card-content\{display:grid;gap:8px;padding:0\}/);assert.doesNotMatch(source,/name="hide_card_background"|card\.hide_background/);});
test("frameless cards retain borders around each task tile",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/dashboard-card.js",import.meta.url),"utf8");assert.match(source,/\.task-row\{border-color:var\(--divider-color\)\}/);});
test("dashboard custom elements are guarded global registrations",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/dashboard-card.js",import.meta.url),"utf8");assert.match(source,/if\(!customElements\.get\("tasks-card"\)\)customElements\.define/);assert.match(source,/if\(!customElements\.get\("tasks-card-editor"\)\)customElements\.define/);assert.doesNotMatch(source,/browser_mod/i);});
test("row menu deletion relies on the shared change event after the mutation",async()=>{const controller=Object.create(TasksBase.prototype),messages=[];controller.confirmAction=async()=>true;controller.ws=async message=>messages.push(message);let loads=0;controller.load=async()=>{loads++;};await controller.deleteTask({task_id:"task",task_name:"Task"});assert.deepEqual(messages,[{type:"tasks/task/delete",task_id:"task"}]);assert.equal(loads,0);});
