import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import test from "node:test";

globalThis.HTMLElement = class {};
globalThis.customElements = {definitions:new Map(),get(name){return this.definitions.get(name);},define(name,value){this.definitions.set(name,value);}};
globalThis.window = {};
globalThis.CustomEvent = class {constructor(type,options){this.type=type;Object.assign(this,options);}};
const fakeElement=localName=>({localName,children:[],attributes:{},listeners:{},append(...children){this.children.push(...children);},setAttribute(name,value){this.attributes[name]=value;},addEventListener(name,listener){this.listeners[name]=listener;}});
globalThis.document = {createElement:fakeElement};
globalThis.fetch = async url => {
  const language=String(url).endsWith("/tasks_strings.json")?"en":String(url).match(/\/([a-z]{2,3})\.json$/)?.[1]||"en";
  const catalog=JSON.parse(readFileSync(new URL(language==="en"?"../../custom_components/tasks/strings.json":`../../custom_components/tasks/translations/${language}.json`,import.meta.url),"utf8"));
  return {ok:true,json:async()=>catalog};
};

const {ready,setLanguage}=await import("../../custom_components/tasks/frontend/localize.js");
await ready;
await setLanguage("en");
const {CURRENT_USER,DEFAULT_CARD_CONFIG,TasksCardEditor,UNASSIGNED,dashboardCardBodyHtml,dashboardCardEditorSchema,dashboardCardOptionsHtml,dashboardTaskRowHtml,dueStatus,filterDashboardTasks,normalizeCardConfig,sortDashboardTasks}=await import("../../custom_components/tasks/frontend/dashboard-card.js");
const {dueDateKey,TasksBase,TasksPanel}=await import("../../custom_components/tasks/frontend/controller.js");
const {TASK_VIEWER_TAG,showTaskViewer}=await import("../../custom_components/tasks/frontend/popup-task-viewer.js");
const {ATTACHMENT_VIEWER_TAG,attachmentPreviewHtml,showAttachmentViewer}=await import("../../custom_components/tasks/frontend/popup-attachment-viewer.js");
const {TASK_EDITOR_TAG,normalizeNotificationTarget,taskEditorFooterHtml,showTaskEditorPopup}=await import("../../custom_components/tasks/frontend/popup-task-editor.js");
const {CONFIRM_POPUP_TAG,showConfirmation}=await import("../../custom_components/tasks/frontend/popup-confirm.js");
const {createActionMenu}=await import("../../custom_components/tasks/frontend/action-menu.js");
const {taskDetailBoxHtml,taskFilesBoxHtml,taskHistoryBoxHtml}=await import("../../custom_components/tasks/frontend/popup-task-editor.js");

const tasks=[
  {task_id:"old",task_name:"Mopping",task_due:"2026-07-20",assignee_id:"alice"},
  {task_id:"today",task_name:"Dishes",task_due:"2026-07-21",assignee_id:null},
  {task_id:"soon",task_name:"Bad",task_due:"2026-07-24",assignee_id:"bob"},
  {task_id:"later",task_name:"Windows",task_due:"2026-08-01",assignee_id:null},
];

test("default config shows overdue and today",()=>assert.deepEqual(filterDashboardTasks(tasks,DEFAULT_CARD_CONFIG,"2026-07-21").map(task=>task.task_id),["old","today"]));
test("due day window includes its future boundary",()=>assert.deepEqual(filterDashboardTasks(tasks,{due_days:3},"2026-07-21").map(task=>task.task_id),["old","today","soon"]));
test("null due day window includes every due date",()=>assert.equal(filterDashboardTasks(tasks,{due_days:null},"2026-07-21").length,4));
test("assignee filter supports multiple selections",()=>assert.deepEqual(filterDashboardTasks(tasks,{due_days:null,assignee_ids:["alice",UNASSIGNED]},"2026-07-21").map(task=>task.task_id),["old","today","later"]));
test("assignee filter resolves the logged-in user dynamically",()=>{assert.deepEqual(filterDashboardTasks(tasks,{due_days:null,assignee_ids:[CURRENT_USER]},"2026-07-21",undefined,"bob").map(task=>task.task_id),["soon"]);assert.deepEqual(filterDashboardTasks(tasks,{due_days:null,assignee_ids:[CURRENT_USER]},"2026-07-21",undefined,"alice").map(task=>task.task_id),["old"]);assert.deepEqual(filterDashboardTasks(tasks,{due_days:null,assignee_ids:[CURRENT_USER]},"2026-07-21").map(task=>task.task_id),[]);});

test("sorting always puts the oldest tasks first with a name tiebreaker without mutation",()=>{const input=[{task_id:"b",task_name:"Zulu",task_due:"2026-07-21"},{task_id:"a",task_name:"Alpha",task_due:"2026-07-21"},{task_id:"c",task_name:"Later",task_due:"2026-07-22"}],original=[...input];assert.deepEqual(sortDashboardTasks(input).map(task=>task.task_id),["a","b","c"]);assert.deepEqual(input,original);});
test("waiting sensor tasks sort after dated tasks and have no due status",()=>{const input=[{task_id:"sensor",task_name:"Problem",task_due:null},{task_id:"dated",task_name:"Dated",task_due:"2026-07-21"}];assert.deepEqual(sortDashboardTasks(input).map(task=>task.task_id),["dated","sensor"]);assert.equal(dueStatus(null,"2026-07-21"),"");});
test("normalization preserves null, sanitizes invalid values, and removes unsupported options",()=>{assert.equal(normalizeCardConfig({due_days:null}).due_days,null);assert.equal(normalizeCardConfig({due_days:-2}).due_days,0);assert.equal(normalizeCardConfig({sort_direction:"desc",hide_card_background:true}).sort_direction,undefined);assert.equal(normalizeCardConfig({hide_card_background:true}).hide_card_background,undefined);});

test("due status separates overdue, today, and future dates",()=>{assert.equal(dueStatus("2026-07-20","2026-07-21"),"overdue");assert.equal(dueStatus("2026-07-21","2026-07-21"),"today");assert.equal(dueStatus("2026-07-22","2026-07-21"),"future");});
test("timed due dates use the displayed time zone for their calendar day",()=>{assert.equal(dueDateKey("2026-07-24T23:46:00Z","Europe/Zurich"),"2026-07-25");assert.equal(dueStatus("2026-07-24T23:46:00Z","2026-07-25","Europe/Zurich"),"today");assert.equal(dueDateKey("2026-07-24"),"2026-07-24");});
test("dashboard uses Home Assistant's current list family",()=>{const html=dashboardCardBodyHtml(dashboardTaskRowHtml(tasks[0],false,"yesterday","overdue"),false);assert.match(html,/^<ha-card><ha-list-base/);assert.match(html,/<ha-list-item-button/);assert.match(html,/slot="headline"/);assert.doesNotMatch(html,/role="button"|tabindex=|<ha-list |<ha-list-item /);});
test("view rows use native supporting text without actions",()=>{const html=dashboardTaskRowHtml(tasks[0],false,"yesterday","overdue","Alice","Laundry tag");assert.doesNotMatch(html,/dots-vertical|row-action-toggle|house|ha-assist-chip|row-action-slot/);assert.match(html,/Mopping/);assert.match(html,/class="task-row overdue"/);assert.match(html,/<span slot="supporting-text"><span class="due-date">yesterday<\/span> • Alice • Laundry tag<\/span>/);});
test("dashboard styles only the status icon and due text",()=>{const html=dashboardTaskRowHtml(tasks[0],false,"Today","today");assert.match(html,/class="task-icon" slot="start"/);assert.match(html,/class="due-date">Today/);const source=readFileSync(new URL("../../custom_components/tasks/frontend/dashboard-card.js",import.meta.url),"utf8");assert.match(source,/\.task-row\.today \.task-icon,\.task-row\.today \.due-date\{color:var\(--warning-color\)\}/);assert.match(source,/\.task-row\.overdue \.task-icon,\.task-row\.overdue \.due-date\{color:var\(--error-color\)\}/);assert.match(source,/\.task-row\.future \.task-icon,\.task-row\.future \.due-date\{color:var\(--success-color\)\}/);assert.doesNotMatch(source,/themeStyles|pillStyles|taskSurfaceStyles|ha-assist-chip/);});
test("dashboard uses a task icon with the existing icon as fallback",()=>{assert.match(dashboardTaskRowHtml({...tasks[0],task_icon:"mdi:washing-machine"},false,"Today","today"),/icon="mdi:washing-machine"/);assert.match(dashboardTaskRowHtml(tasks[0],false,"Today","today"),/icon="mdi:clipboard-check-outline"/);});
test("dashboard delegates rows to Home Assistant without custom metadata controls",()=>{const dashboard=readFileSync(new URL("../../custom_components/tasks/frontend/dashboard-card.js",import.meta.url),"utf8"),list=readFileSync(new URL("../../custom_components/tasks/frontend/sidebar-task-list.js",import.meta.url),"utf8");assert.match(dashboard,/<ha-list-item/);assert.doesNotMatch(dashboard,/<ha-assist-chip/);assert.match(list,/hass-tabs-subpage-data-table/);assert.doesNotMatch(list,/pillStyles\(\)|taskRow\(/);assert.doesNotMatch(dashboard,/pillIconCss\(\)/);});
test("edit rows reserve a native action-menu slot",()=>{const html=dashboardTaskRowHtml(tasks[0],true,"yesterday","overdue");assert.match(html,/class="row-action-slot"/);assert.doesNotMatch(html,/row-action-menu|style=/);});
test("shared action menu uses native HA dropdown controls and dispatches actions",()=>{let edited=0,removed=0,stopped=0;const menu=createActionMenu({label:"Task actions",edit:()=>edited++,remove:()=>removed++});assert.equal(menu.localName,"ha-dropdown");assert.deepEqual(menu.children.map(child=>child.localName),["ha-icon-button","ha-dropdown-item","ha-dropdown-item"]);assert.equal(menu.children[0].attributes["aria-label"],"Task actions");assert.equal(menu.children[2].attributes.variant,"danger");menu.listeners.pointerdown({stopPropagation:()=>stopped++});menu.listeners.click({stopPropagation:()=>stopped++});menu.listeners["wa-select"]({stopPropagation:()=>stopped++,detail:{item:{value:"edit"}}});menu.listeners["wa-select"]({stopPropagation:()=>stopped++,detail:{item:{value:"delete"}}});assert.equal(edited,1);assert.equal(removed,1);assert.equal(stopped,4);});
test("editor update emits a dashboard-local config change",()=>{const editor=Object.create(TasksCardEditor.prototype);editor.config={...DEFAULT_CARD_CONFIG};let event;editor.dispatchEvent=value=>{event=value;};editor.update({show_action_menu:true,assignee_ids:["alice"]});assert.equal(event.type,"config-changed");assert.equal(event.detail.config.show_action_menu,true);assert.deepEqual(event.detail.config.assignee_ids,["alice"]);});
test("dashboard editor uses popup-style switches and titled native form groups",()=>{const schema=dashboardCardEditorSchema([{id:"alice",name:"Alice"}]),content=schema[0],filter=schema[1],contentGroup=content.schema[0],dueGroup=filter.schema[0],assigneeGroup=filter.schema[1],secondaryInfo=contentGroup.schema[1],dueDays=dueGroup.schema[1],assigneeIds=assigneeGroup.schema[1],optionsHtml=dashboardCardOptionsHtml();assert.deepEqual(schema.map(field=>field.name),["secondary","filter"]);assert.ok(schema.every(field=>field.type==="expandable"&&field.flatten===true));assert.equal(content.title,"Content");assert.match(optionsHtml,/ha-expansion-panel class="editor-options" outlined expanded/);assert.match(optionsHtml,/mdi:tune/);assert.deepEqual([...optionsHtml.matchAll(/data-option="([^"]+)"/g)].map(match=>match[1]),["show_action_menu","show_add_task"]);assert.equal((optionsHtml.match(/<ha-switch/g)||[]).length,2);assert.deepEqual([contentGroup,dueGroup,assigneeGroup].map(group=>group.schema[0].type),["constant","constant","constant"]);assert.deepEqual([contentGroup.schema[0].name,dueGroup.schema[0].name,assigneeGroup.schema[0].name],["content_title","due_filter_title","assignee_filter_title"]);assert.equal(secondaryInfo.selector.select.multiple,true);assert.equal(secondaryInfo.selector.select.reorder,true);assert.deepEqual(secondaryInfo.selector.select.options.map(option=>option.value),["due","assignee","nfc_tag","labels"]);assert.equal(dueDays.selector.number.mode,"box");assert.equal(assigneeIds.selector.select.multiple,true);assert.deepEqual(assigneeIds.selector.select.options.map(option=>option.value),[CURRENT_USER,UNASSIGNED,"alice"]);assert.equal(assigneeIds.selector.select.options[0].label,"Logged-in user");const source=readFileSync(new URL("../../custom_components/tasks/frontend/dashboard-card.js",import.meta.url),"utf8");assert.match(source,/\.editor-option-list\{display:flex;flex-direction:column;gap:4px;padding:12px\}/);assert.match(source,/\.editor-option\{[^}]*min-height:48px/);assert.match(source,/control\.addEventListener\("change"/);assert.match(source,/form\.setAttribute\("style","--ha-space-6:8px"\)/);assert.match(source,/content_title:t\("card\.state_content"\)/);assert.match(source,/secondary_info:t\("card\.add_filter"\)/);assert.match(source,/due_days:t\("card\.days"\)/);assert.match(source,/form\.schema=dashboardCardEditorSchema\(this\.users\)/);assert.match(source,/form\.addEventListener\("value-changed"/);assert.doesNotMatch(source,/<select name="mode"|input type="checkbox"|class="choices"|card\.mode/);});
test("dashboard display options independently control actions",()=>{const defaults=normalizeCardConfig({});assert.equal(defaults.show_action_menu,false);assert.equal(defaults.show_add_task,false);const enabled=normalizeCardConfig({show_action_menu:true,show_add_task:true});assert.equal(enabled.show_action_menu,true);assert.equal(enabled.show_add_task,true);assert.match(dashboardTaskRowHtml(tasks[0],true,"Today","today","Alex","Tag"),/row-action-slot/);assert.match(dashboardCardBodyHtml("<ha-list-item-button></ha-list-item-button>",true),/class="add-task"/);});
test("card editor keeps an expanded form mounted when Home Assistant echoes its config",()=>{const editor=Object.create(TasksCardEditor.prototype);editor.config=normalizeCardConfig({show_action_menu:true});let renders=0;editor.render=()=>{renders++;};editor.shadowRoot={querySelector:selector=>selector==="ha-form"?{}:null};editor.setConfig({...editor.config});assert.equal(renders,0);editor.setConfig({...editor.config,show_add_task:true});assert.equal(renders,1);});
test("repeated hass updates do not rerender and steal editor focus",()=>{const editor=Object.create(TasksCardEditor.prototype);editor.loaded=true;let renders=0;editor.render=()=>{renders++;};Object.getOwnPropertyDescriptor(TasksCardEditor.prototype,"hass").set.call(editor,{user:{}});assert.equal(renders,0);});
test("shared controller reloads from Tasks events",async()=>{const controller=Object.create(TasksBase.prototype);controller.eventUnsubscribe=null;controller.eventSubscriptionToken=0;let listener,eventType,loads=0;controller._hass={connection:{subscribeEvents:async(callback,type)=>{listener=callback;eventType=type;return()=>{};}}};controller.load=async()=>{loads++;};await controller.subscribeEvents();assert.equal(eventType,"tasks_event");await listener({data:{action:"updated",resource_type:"task"}});assert.equal(loads,1);});
test("shared controller removes stale event subscriptions",async()=>{const controller=Object.create(TasksBase.prototype);controller.eventUnsubscribe=null;controller.eventSubscriptionToken=0;let removed=0;controller._hass={connection:{subscribeEvents:async()=>()=>{removed++;}}};await controller.subscribeEvents();controller.unsubscribeEvents();assert.equal(removed,1);assert.equal(controller.eventUnsubscribe,null);});
test("ordinary hass updates no longer reload task data",async()=>{const controller=Object.create(TasksBase.prototype),descriptor=Object.getOwnPropertyDescriptor(TasksBase.prototype,"hass"),settle=()=>new Promise(resolve=>setImmediate(resolve));controller.loaded=true;controller.eventUnsubscribe=()=>{};controller.eventSubscriptionToken=0;let loads=0,renders=0;controller.load=async()=>{loads++;};controller.render=()=>{renders++;};const connection={subscribeEvents:async()=>()=>{}};descriptor.set.call(controller,{connection,locale:{language:"en"},states:{"todo.tasks":{state:"1"}}});await settle();descriptor.set.call(controller,{connection,locale:{language:"en"},states:{"todo.tasks":{state:"0"}}});await settle();assert.equal(loads,0);assert.equal(renders,0);});
test("concurrent loads are coalesced into one pending reload",async()=>{const controller=Object.create(TasksBase.prototype);controller._hass={};controller.loading=true;controller.reloadPending=false;await controller.load();await controller.load();assert.equal(controller.reloadPending,true);});
test("panel uses an unregistered shared base instead of becoming the card base",async()=>{const {TasksCard}=await import("../../custom_components/tasks/frontend/dashboard-card.js");assert.equal(Object.getPrototypeOf(TasksPanel),TasksBase);assert.equal(Object.getPrototypeOf(TasksCard),TasksBase);assert.notEqual(Object.getPrototypeOf(TasksCard),TasksPanel);});
test("task viewer opens through Home Assistant's native show-dialog contract",()=>{let event;const controller={dispatchEvent:value=>{event=value;}};showTaskViewer(controller,tasks[0]);assert.equal(event.type,"show-dialog");assert.equal(event.bubbles,true);assert.equal(event.composed,true);assert.equal(event.detail.dialogTag,TASK_VIEWER_TAG);assert.equal(event.detail.dialogParams.task,tasks[0]);});
test("task viewer delegates descriptions directly to native Home Assistant markdown",()=>{const viewer=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-viewer.js",import.meta.url),"utf8");assert.match(viewer,/<ha-markdown breaks><\/ha-markdown>/);assert.match(viewer,/markdown\.content=task\.task_description/);assert.doesNotMatch(viewer,/ha-faded|content-resize|faded-content|markdown\(task\.description\)|markdownInline|export const markdown/);});
test("task viewer uses native two-line list rows for files and history",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-viewer.js",import.meta.url),"utf8");assert.match(source,/\.ht-content\{color:var\(--secondary-text-color\)/);assert.match(source,/<p class="recurrence ht-content">/);assert.match(source,/<textarea class="completion-notes ht-content"/);assert.match(source,/\$\{taskFilesBoxHtml\(controller,task\)\}\$\{taskHistoryBoxHtml\(controller,null\)\}/);assert.match(source,/<ha-expansion-panel outlined/);assert.match(source,/<ha-list-base class="file-list">/);assert.match(source,/<\$\{tag\} data-file="\$\{id\}" class="file-row"\$\{link\}><ha-icon slot="start" icon="mdi:file-outline"><\/ha-icon><span slot="headline">\$\{name\}<\/span><span slot="supporting-text">/);assert.match(source,/<ha-list-base class="history-list">/);assert.doesNotMatch(source,/VIEWER_FILE_GRID|grid-template-columns|task\.planning|task\.description|task\.completion_notes[^"]*\),notes|<details|<summary/);});
test("task detail box helper delegates header typography and outlines to Home Assistant",()=>{assert.match(taskDetailBoxHtml("Name","Task",{expanded:true}),/^<ha-expansion-panel outlined expanded>/);assert.match(taskDetailBoxHtml("Files","None",{className:"files-box"}),/^<ha-expansion-panel outlined class="files-box">/);assert.doesNotMatch(taskDetailBoxHtml("Name","Task"),/slot="header" class=/);});
test("completion confirmation is owned by the task popup",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-viewer.js",import.meta.url),"utf8");assert.match(source,/class TasksPopupCompletionConfirm/);assert.match(source,/confirmCompletion\(this,this\.task\)/);assert.doesNotMatch(source,/native-form-dialog|controller\.confirmAction/);});
test("completion confirmation uses an existing translated action label",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-viewer.js",import.meta.url),"utf8");assert.match(source,/class="confirm"[\s\S]*?t\("task\.completed"\)/);assert.doesNotMatch(source,/t\("task\.complete"\)/);});
test("completion notes reuse the editor textarea formatting at their current viewer position",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-viewer.js",import.meta.url),"utf8");assert.match(source,/\.value\|\|""\)\.trim\(\)\|\|null/);assert.match(source,/<textarea class="completion-notes ht-content" style="resize:vertical" aria-label=/);assert.match(source,/textarea\{box-sizing:border-box;min-height:60px/);assert.doesNotMatch(source,/\.completion-notes\{/);assert.match(source,/\$\{description\}\$\{notes\}\$\{taskFilesBoxHtml/);assert.doesNotMatch(source,/<ha-textarea|<wa-textarea/);});
test("task viewer places outlined chips first and keeps due in the first chip",()=>{const viewer=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-viewer.js",import.meta.url),"utf8"),main=readFileSync(new URL("../../custom_components/tasks/frontend/controller.js",import.meta.url),"utf8");assert.match(viewer,/due=task\.task_due\?`<ha-assist-chip label="\$\{esc\(controller\.date\(task\.task_due\)\)\}"><ha-icon slot="icon" icon="mdi:calendar"/);assert.match(viewer,/<div class="content"><ha-chip-set>\$\{due\}<ha-assist-chip label="\$\{esc\(assignee[\s\S]*?<\/ha-chip-set><p class="recurrence ht-content">/);assert.doesNotMatch(viewer,/<ha-assist-chip filled|chip\.filled/);assert.doesNotMatch(main,/next=task\.task_due|t\("task\.due"\).*this\.date/);});
test("task viewer appends NFC, file count, and labels in that order",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-viewer.js",import.meta.url),"utf8");const nfc=source.indexOf("chip.innerHTML='<ha-icon slot=\"icon\" icon=\"mdi:nfc\""),files=source.indexOf("files.innerHTML='<ha-icon slot=\"icon\" icon=\"mdi:file-outline\""),labels=source.indexOf("chip.innerHTML='<ha-icon slot=\"icon\" icon=\"mdi:label-outline\"");assert.ok(nfc>0);assert.ok(files>nfc);assert.ok(labels>files);assert.match(source,/fileCount=this\.controller\.attachments\.filter\(file=>file\.task_id===this\.task\.task_id\)\.length/);assert.match(source,/files\.label=String\(fileCount\)/);});
test("task viewer appends labels and the assigned tag as outlined native chips",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-viewer.js",import.meta.url),"utf8");assert.match(source,/this\.render\(\);[\s\S]*?this\.addAssignmentChips\(\);this\.loadHistory\(\)/);assert.match(source,/createElement\("ha-assist-chip"\)/);assert.doesNotMatch(source,/chip\.filled=true/);assert.match(source,/slot="icon" icon="mdi:label-outline"/);assert.match(source,/slot="icon" icon="mdi:nfc"/);assert.match(source,/controller\.labelNames\(this\.task\)/);assert.match(source,/controller\.tagName\(this\.task\)/);assert.doesNotMatch(source,/pill/i);});
test("task viewer omits labels deleted from Home Assistant",()=>{const controller=Object.create(TasksBase.prototype);controller.labels=[{label_id:"known",name:"Known"}];assert.deepEqual(controller.labelNames({label_ids:["known","deleted"]}),["Known"]);});
test("task viewer omits NFC tags deleted from Home Assistant",()=>{const controller=Object.create(TasksBase.prototype);controller.tags=[{id:"known",name:"Known"}];assert.equal(controller.tagName({nfc_tag_id:"known"}),"Known");assert.equal(controller.tagName({nfc_tag_id:"deleted"}),"");});
test("task editor loads only existing Home Assistant users and tags into selects",()=>{const main=readFileSync(new URL("../../custom_components/tasks/frontend/controller.js",import.meta.url),"utf8"),editor=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.match(main,/this\.ws\(\{type:"tag\/list"\}\)/);assert.match(main,/this\.tags=Array\.isArray\(tags\)\?tags:\[\]/);assert.match(editor,/assigneeId=knownReferenceId\(t\.assignee_id,this\.users\)\|\|""/);assert.match(editor,/nfcTagId=knownReferenceId\(t\.nfc_tag_id,this\.tags\)\|\|""/);assert.match(editor,/tagOptions=\[\.\.\.this\.tags\]/);assert.match(editor,/\["assignee_id",tr\("task\.user"\),assigneeId/);assert.match(editor,/\["nfc_tag_id",tr\("task\.nfc_tag_id"\),nfcTagId/);assert.match(editor,/tr\("task\.no_nfc_tag"\)/);assert.doesNotMatch(editor,/tagOptions\.push/);});
test("task editor places native icon and multiple-label selectors last in Assignment",()=>{const main=readFileSync(new URL("../../custom_components/tasks/frontend/controller.js",import.meta.url),"utf8"),editor=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.match(main,/this\.ws\(\{type:"config\/label_registry\/list"\}\)/);assert.match(editor,/<label data-field="\$\{key\}">\$\{caption\}<input[^>]+><ha-selector><\/ha-selector><\/label>/);assert.match(editor,/\["task_icon",tr\("task\.icon"\)[\s\S]*?"icon"/);assert.match(editor,/\["label_ids",tr\("task\.labels"\)[\s\S]*?"labels"/);assert.match(editor,/iconSelector\.selector=\{icon:\{\}\}/);assert.match(editor,/labelIds=knownLabelIds\(JSON\.parse\(labelInput\.value\|\|"\[\]"\),this\.labels\)/);assert.match(editor,/labelInput\.value=JSON\.stringify\(labelIds\)/);assert.match(editor,/labelSelector\.key="label_ids"/);assert.doesNotMatch(editor,/labelSelector\.label=/);assert.match(editor,/labelSelector\.selector=\{label:\{multiple:true\}\}/);assert.doesNotMatch(editor,/labelSelector\.selector=\{select:/);assert.match(editor,/labelSelector\.value=labelIds/);assert.match(editor,/JSON\.stringify\(event\.detail\?\.value\|\|\[\]\)/);assert.match(editor,/fields=\[form\.querySelector\('\[data-field="assignee_id"\]'\),form\.querySelector\('\[data-field="nfc_tag_id"\]'\),iconField,labelField\]/);assert.match(editor,/task_icon:v\.task_icon\|\|null/);assert.match(editor,/label_ids:JSON\.parse/);});
test("editor fields assign typography classes by role",()=>{const controller=Object.create(TasksBase.prototype);assert.match(controller.field(["name","Name","",true]),/class="ht-label-medium"[\s\S]*class="ht-content"/);assert.match(controller.field(["schedule_type","Calculate due date","fixed",true,"select",[["fixed","Calendar"]]]),/class="ht-label-normal"[\s\S]*class="ht-content"/);assert.match(controller.field(["manufacturer","Manufacturer",""]),/class="ht-label-medium"[\s\S]*class="ht-content"/);});
test("prefilled planning fields stay required without displaying asterisks",()=>{const controller=Object.create(TasksBase.prototype);for(const field of [["schedule_type","Calculation","sliding",true,"select",[["sliding","Sliding"]]],["schedule_unit","Unit","monthly",true,"select",[["monthly","Monthly"]]],["schedule_interval","Interval",1,true,"number"]]){const html=controller.field(field);assert.match(html,/ required/);assert.doesNotMatch(html,/class="required"/);}assert.match(controller.field(["task_name","Name","",true]),/class="required"/);});
test("editor keeps name and optional description as placeholders above the expandable sections",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.match(source,/createElement\("ha-expansion-panel"\)/);assert.match(source,/panel\.outlined=true/);assert.match(source,/panel\.expanded=expanded/);assert.match(source,/\["task_name",tr\("task\.name"\)/);assert.match(source,/\["task_description",tr\("task\.optional_description"\)/);assert.match(source,/\[\[name,tr\("task\.name"\)\],\[description,tr\("task\.optional_description"\)\]\]/);assert.match(source,/displayPlaceholder=`\$\{placeholder\}\$\{control\.required\?" \*":""\}`/);assert.match(source,/control\.placeholder=displayPlaceholder/);assert.match(source,/field\.querySelector\(":scope > span"\)\?\.remove\(\)/);assert.match(source,/form\.prepend\(name,description\)/);assert.doesNotMatch(source,/name-box|description-box/);assert.match(source,/header\.slot="header"/);assert.doesNotMatch(source,/prepareDetails|details-toggle|MutationObserver/);});
test("notification targets use Home Assistant's native device and navigation selectors",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.match(source,/selector\.label=tr\("task\.notification_devices"\)/);assert.match(source,/selector\.selector=\{device:\{multiple:true,filter:\[\{integration:"mobile_app"\}\]\}\}/);assert.match(source,/selector\.value=notification\.target\.device_id\|\|\[\]/);assert.match(source,/notification\.target=normalizeNotificationTarget\(\{device_id:event\.detail\?\.value\}\);selector\.value=/);assert.match(source,/createElement\("ha-switch"\)/);assert.match(source,/notification_persistent_description/);assert.match(source,/notification_critical_description/);assert.match(source,/routeLabel\.textContent=tr\("task\.notification_route"\)/);assert.match(source,/routeField\.append\(routeLabel,route\)/);assert.match(source,/route\.selector=\{navigation:null\}/);assert.match(source,/route\.required=false/);assert.match(source,/route\.value=notification\.route\|\|undefined/);assert.match(source,/route:t\.notification_route\|\|null/);assert.match(source,/notification\.route=String\(event\.detail\?\.value\|\|""\)\.trim\(\)\|\|null/);assert.match(source,/content\.append\(options,selector,routeField\)/);assert.match(source,/task\.notification_persistent/);assert.match(source,/task\.notification_critical/);assert.match(source,/notification_route:notification\.route/);assert.match(source,/notification_target:notification\.target/);assert.match(source,/this\.arrangeNotifications\(modal,notification\)/);assert.doesNotMatch(source,/routeOptions|Add target|Ziel hinzuf/);});
test("notification target normalization keeps unique valid device ids",()=>{assert.deepEqual(normalizeNotificationTarget({device_id:["phone","phone","tablet",null]}),{device_id:["phone","tablet"]});assert.deepEqual(normalizeNotificationTarget({}),{});});
test("editors and confirmations use registered native dialog contracts",()=>{const events=[],controller={dispatchEvent:event=>events.push(event)};showTaskEditorPopup(controller,{title:"Editor",fields:[]});showConfirmation(controller,{title:"Delete",message:"Sure?",confirmLabel:"Delete"});assert.equal(events[0].detail.dialogTag,TASK_EDITOR_TAG);assert.equal(events[1].detail.dialogTag,CONFIRM_POPUP_TAG);assert.ok(events.every(event=>event.bubbles&&event.composed));});
test("native form dialogs keep their styles local and no longer post-process collapsible sections",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8"),controller=readFileSync(new URL("../../custom_components/tasks/frontend/controller.js",import.meta.url),"utf8");assert.match(source,/\.ht-label-medium\{color:var\(--primary-text-color\)/);assert.doesNotMatch(source,/dialogLayoutStyles|prepareDetails|details-toggle/);assert.doesNotMatch(controller,/typographyStyles|themeStyles|buttonThemeStyles|formStyles/);});
test("native editor actions use the same adaptive-dialog footer as the viewer",()=>{const html=taskEditorFooterHtml();assert.match(html,/ha-dialog-footer slot="footer"/);assert.match(html,/ha-button class="save" slot="primaryAction" variant="brand"/);assert.doesNotMatch(html,/<button/);});
test("native form source renders its footer directly without a legacy inline save action",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.doesNotMatch(source,/mountFooter|inlineSave|class="actions"|class="primary"/);assert.match(source,/\$\{taskEditorFooterHtml\(\)\}<\/ha-adaptive-dialog>/);});
test("frontend shells no longer contain legacy dialog placeholders",()=>{for(const file of ["controller.js","sidebar-task-list.js","dashboard-card.js"]){const source=readFileSync(new URL(`../../custom_components/tasks/frontend/${file}`,import.meta.url),"utf8");assert.doesNotMatch(source,/class="dialogs"|class="overlay"|modal-header|modal-close/);}});
test("attachment rows use the full filename",()=>{const controller=Object.create(TasksBase.prototype);controller.signedFiles=new Map([["file","/signed/file"]]);const html=controller.fileLink({attachment_id:"file",filename:"a very long filename.pdf"});assert.match(html,/<a class="filename file-open" data-file-open="file" href="\/signed\/file"[^>]*>a very long filename\.pdf<\/a>/);assert.match(html,/overflow-wrap:anywhere/);assert.doesNotMatch(html,/filename-base|filename-extension|text-overflow|target="_blank"|<button/);});
test("file open handling ignores clicks from the delete action",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/controller.js",import.meta.url),"utf8");assert.match(source,/event\.composedPath\(\)\.some\(node=>node\.classList\?\.contains\("remove"\)\)/);});
test("signed attachment URLs are loaded only when a task popup opens",async()=>{const controller=Object.create(TasksBase.prototype),messages=[];controller.signedFiles=new Map();controller.ws=async message=>{messages.push(message);return {signed_files:{file:"/signed/file"}};};await controller.ensureTaskFileUrls("task");assert.deepEqual(messages,[{type:"tasks/attachment/urls",task_id:"task"}]);assert.equal(controller.signedFiles.get("file"),"/signed/file");const main=readFileSync(new URL("../../custom_components/tasks/frontend/controller.js",import.meta.url),"utf8"),editor=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.doesNotMatch(main,/d\.signed_files/);assert.match(main,/async taskViewer\(task\)\{try\{await this\.ensureTaskFileUrls\(task\.task_id\)/);assert.match(editor,/async taskEditor\(task=null\)\{if\(task\)try\{await this\.ensureTaskFileUrls\(task\.task_id\)/);});
test("stored files use native two-line link rows with a separate end action",()=>{const controller={attachments:[{attachment_id:"file",task_id:"task",filename:"filename.pdf",size:1024}],signedFiles:new Map([["file","/signed/file"]]),size:()=>"1 KB"},task={task_id:"task"},editor=taskFilesBoxHtml(controller,task,{editable:true});assert.match(editor,/<ha-list-base class="file-list">/);assert.match(editor,/<ha-list-item-button data-file="file" class="file-row " data-file-open="file" href="\/signed\/file">/);assert.match(editor,/<ha-icon slot="start" icon="mdi:file-outline"><\/ha-icon><span slot="headline">filename\.pdf<\/span><span slot="supporting-text">1 KB<\/span>/);assert.match(editor,/<ha-icon-button slot="end" class="editor-action remove danger"/);assert.match(editor,/mdi:delete/);assert.doesNotMatch(editor,/grid-template-columns|file-row-link|ha-checkbox/);});
test("popup expansion panels suppress Home Assistant's click fill via its own variable",()=>{for(const file of ["popup-task-viewer.js","popup-task-editor.js","popup-settings.js"]){const source=readFileSync(new URL(`../../custom_components/tasks/frontend/${file}`,import.meta.url),"utf8");assert.match(source,/ha-expansion-panel\{--input-fill-color:transparent\}/);}});
test("editable files use Home Assistant's native multiple file upload component",()=>{const controller={attachments:[],fileLink:()=>"",size:()=>""},html=taskFilesBoxHtml(controller,{task_id:"task"},{editable:true});assert.match(html,/<ha-selector class="file-upload-loader" hidden><\/ha-selector><ha-file-upload class="attachment-upload"><\/ha-file-upload>/);assert.doesNotMatch(html,/<input type="file"|attachment-drop-zone|choose-files/);const editor=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8"),main=readFileSync(new URL("../../custom_components/tasks/frontend/controller.js",import.meta.url),"utf8");assert.match(editor,/loader\.selector=\{file:\{accept:"\*\/\*"\}\}/);assert.match(editor,/upload\.multiple=true/);assert.match(editor,/upload\.addEventListener\("file-picked"/);assert.match(editor,/editor\.stagedFiles\.push/);assert.match(editor,/while\(editor\.stagedFiles\.length\)/);assert.match(editor,/this\.uploadNativeFile\(file\)/);assert.match(editor,/this\.attachUploadedFile\(editor\.task\.task_id,fileId\)/);assert.doesNotMatch(editor,/dropZone\.ondrop|dataTransfer\.files/);assert.match(main,/fetchWithAuth\("\/api\/file_upload"/);assert.match(main,/type:"tasks\/attachment\/create"/);assert.doesNotMatch(main,/\/api\/tasks\/upload/);});
test("new task editor stages files in native base rows before upload",()=>{const controller={attachments:[],signedFiles:new Map(),size:value=>`${value} B`},html=taskFilesBoxHtml(controller,null,{editable:true,staged:[{name:"draft.txt",size:5}]});assert.match(html,/<ha-list-item-base data-staged="0" class="file-row">/);assert.match(html,/<ha-icon slot="start" icon="mdi:file-outline"><\/ha-icon><span slot="headline">draft\.txt<\/span><span slot="supporting-text">5 B<\/span>/);assert.match(html,/<ha-icon-button slot="end" class="editor-action remove danger"/);assert.doesNotMatch(html,/ha-checkbox/);const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.match(source,/this\.mountDetails\(modal,editor,pendingFiles,pendingHistory\)/);assert.match(source,/pendingFiles=new Set\(\)/);assert.doesNotMatch(source,/ha-list-selectable|ha-list-item-option|file\.delete_positions/);assert.match(source,/event\.preventDefault\(\);event\.stopPropagation\(\)/);assert.match(source,/const wasNew=!editor\.task;[\s\S]*?editor\.task=await this\.ws/);assert.match(source,/if\(wasNew\)createdInEditor=true/);assert.match(source,/if\(createdInEditor&&editor\.task\)\{try\{await this\.ws\(\{type:"tasks\/task\/delete"/);});
test("viewer and editor history use native headline and supporting text rows",()=>{const controller=Object.create(TasksBase.prototype);controller.locale=()=>"en";controller.historyTime=()=>"12:00";controller.date=value=>value;const entry={history_entry_id:"entry",completion_date:"2026-07-22",user_name:"User",notes:"Comment"},viewer=controller.historyRow(entry),editor=controller.historyRow(entry,true);for(const html of [viewer,editor]){assert.match(html,/^<ha-list-item-base class="history-entry"/);assert.match(html,/<ha-icon slot="start" icon="mdi:history"><\/ha-icon>/);assert.match(html,/<span slot="headline">2026-07-22, 12:00 · User<\/span>/);assert.match(html,/<span slot="supporting-text"[^>]*>Comment<\/span>/);}assert.doesNotMatch(viewer,/editor-action|mdi:delete/);assert.match(editor,/<ha-icon-button slot="end" class="editor-action remove danger"/);assert.match(editor,/mdi:delete/);assert.doesNotMatch(editor,/grid-template-columns|min-height:48px/);});
test("shared file and history boxes expose destructive controls only in editor mode",()=>{const controller={attachments:[{attachment_id:"file",task_id:"task",filename:"file.txt",size:4}],signedFiles:new Map([["file","/file"]]),size:()=>"4 B",historyRow:(_entry,editable)=>`<span>${editable}</span>`},task={task_id:"task"};assert.doesNotMatch(taskFilesBoxHtml(controller,task),/class="editor-action/);assert.match(taskFilesBoxHtml(controller,task,{editable:true}),/class="editor-action remove danger"/);assert.doesNotMatch(taskHistoryBoxHtml(controller,[{history_entry_id:"history"}]),/>true</);assert.match(taskHistoryBoxHtml(controller,[{history_entry_id:"history"}],{editable:true}),/>true</);});
test("planning schedule_interval uses an equal-height theme-aware stepper",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.match(source,/mountIntervalStepper\(field\)/);assert.match(source,/schedule-select,.schedule_interval-stepper\{[^}]*height:44px/);assert.match(source,/task\.interval_decrease/);assert.match(source,/task\.interval_increase/);assert.match(source,/ha-color-fill-neutral-quiet-hover/);assert.match(source,/event\.key==="ArrowUp"/);assert.match(source,/event\.key==="ArrowDown"/);});
test("planning groups visible controls by trigger",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.match(source,/\["sliding",L\.sliding\],\["fixed",L\.fixed\],\["sensor",tr\("task\.problem"\)\]/);assert.match(source,/problemSelector\.selector=\{entity:\{filter:\[\{domain:"binary_sensor"\}\]\}\}/);assert.match(source,/const renderAfterCompletion=\(\)=>\{[\s\S]*?row\.hidden=false;[\s\S]*?firstDueBox\.hidden=false;[\s\S]*?preview\.hidden=true;[\s\S]*?problem\.hidden=true;/);assert.match(source,/const renderFixedSchedule=\(\)=>\{[\s\S]*?row\.hidden=false;[\s\S]*?firstDueBox\.hidden=true;[\s\S]*?preview\.hidden=false;[\s\S]*?problem\.hidden=true;/);assert.match(source,/const renderProblemTrigger=\(\)=>\{[\s\S]*?row\.hidden=true;[\s\S]*?rule\.hidden=true;[\s\S]*?preview\.hidden=true;[\s\S]*?problem\.hidden=false;/);assert.match(source,/firstDueTitle\.textContent=tr\("task\.first_due"\)/);assert.match(source,/mode\.value==="sliding"\)firstDueText\.textContent=previewDates\[0\]\?this\.date\(previewDates\[0\]\):"–"/);assert.doesNotMatch(source,/save\.disabled=sensor/);});
test("fixed planning places its rule before the due preview without duplication",()=>{const editor=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8"),controller=readFileSync(new URL("../../custom_components/tasks/frontend/controller.js",import.meta.url),"utf8");assert.match(editor,/content\.append\(recurrence,row,options,rule\)/);assert.match(editor,/content\.append\(firstDueBox,preview,problem\)/);assert.match(editor,/renderRule=\(\)=>\{rule\.textContent=this\.scheduleText\(scheduleValue\(\)\)/);assert.doesNotMatch(controller,/editorScheduleHtml[^}]*scheduleText/);});
test("planning hidden state overrides visible layout rules",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.match(source,/\.schedule-box \[hidden\]\{display:none!important\}/);});
test("planning places the labelled interval before its plural unit",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.match(source,/\["schedule_interval",tr\("task\.schedule_unit"\)/);assert.doesNotMatch(source,/intervalLabel/);assert.match(source,/unitLabel\.style\.visibility="hidden"/);assert.match(source,/row\.append\(schedule_interval,schedule_unit\)/);assert.doesNotMatch(source,/row\.append\(fixed\?/);});
test("planning units follow the interval number",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.match(source,/singular=Number\(form\.elements\.schedule_interval\.value\)===1/);assert.match(source,/daily:"task\.day",\s*weekly:"task\.week",\s*monthly:"task\.month",\s*yearly:"task\.year"/);assert.match(source,/option\.textContent=singular\s*\?tr\(singularKeys\[option\.value\]\)\s*:pluralNames\[option\.value\]/);});
test("planning shows no calculation progress copy",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.doesNotMatch(source,/task\.calculating_task_dues/);});
test("planning keeps loaded due values visible during recalculation",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.match(source,/if\(!summary\.dataset\.ready\)\{summary\.innerHTML=/);assert.match(source,/summary\.dataset\.ready="true"/);assert.match(source,/summary\.setAttribute\("aria-busy","true"\)/);assert.match(source,/request===previewRequest/);assert.doesNotMatch(source,/firstDueText\.textContent=""/);});
test("planning loads 24 due dates once and reveals all of them with one click",()=>{const editor=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8"),api=readFileSync(new URL("../../custom_components/tasks/task_api.py",import.meta.url),"utf8");assert.match(api,/PREVIEW_COUNT = 24/);assert.match(editor,/previewDates=result\.task_dues/);assert.match(editor,/previewDates\.slice\(0,visibleCount\)/);assert.match(editor,/more\.onclick=\(\)=>\{\s*visibleCount=previewDates\.length;\s*renderSummary\(\);\s*\}/);assert.doesNotMatch(editor,/preview_next_due",\.\.\.task,count:/);});
test("problem trigger persists only its binary sensor",()=>{const editor=readFileSync(new URL("../../custom_components/tasks/frontend/popup-task-editor.js",import.meta.url),"utf8");assert.match(editor,/schedulePayload=v\.schedule_type==="sensor"\?\{schedule_type:"sensor",problem_sensor:schedule\.problem_sensor\}/);assert.match(editor,/problemSelector\.value=schedule\.problem_sensor\|\|undefined/);assert.match(editor,/problemSelector\.required=true/);});
test("attachments open through a native popup with media previews and no footer",()=>{let event;const dispatcher={dispatchEvent:value=>{event=value;}};const file={attachment_id:"file",filename:"photo.jpg",content_type:"image/jpeg"};showAttachmentViewer(dispatcher,file,"/signed/file");assert.equal(event.type,"show-dialog");assert.equal(event.detail.dialogTag,ATTACHMENT_VIEWER_TAG);assert.equal(event.detail.dialogParams.file,file);assert.match(attachmentPreviewHtml(file,"/signed/file"),/<img /);assert.match(attachmentPreviewHtml({...file,content_type:"video/mp4"},"/signed/file"),/<video /);assert.match(attachmentPreviewHtml({...file,content_type:"audio/mpeg"},"/signed/file"),/<audio /);assert.match(attachmentPreviewHtml({...file,content_type:"application\/pdf"},"/signed/file"),/<iframe /);const source=readFileSync(new URL("../../custom_components/tasks/frontend/popup-attachment-viewer.js",import.meta.url),"utf8");assert.match(source,/ha-adaptive-dialog/);assert.doesNotMatch(source,/ha-dialog-footer|attachment\.download|class="download"|mdi:download/);});
test("task editor popup does not expose delete actions",()=>{assert.equal(typeof TasksBase.prototype.mountTaskActions,"undefined");});
test("dashboard add action is the final native list row",()=>{const html=dashboardCardBodyHtml('<ha-list-item-button class="task-row"></ha-list-item-button>',true);assert.ok(html.indexOf("add-task")>html.indexOf("task-row"));assert.match(html,/<ha-list-item-button class="add-task"><ha-icon slot="start" icon="mdi:plus"><\/ha-icon><span slot="headline">Add task<\/span><\/ha-list-item-button><\/ha-list-base><\/ha-card>/);const source=readFileSync(new URL("../../custom_components/tasks/frontend/dashboard-card.js",import.meta.url),"utf8");assert.match(source,/add\.onclick=\(\)=>\{add\.blur\(\);this\.taskEditor\(null\);\}/);assert.doesNotMatch(source,/border:2px dashed|<ha-button class="add-task"|\.add-task\{/);});

test("dashboard uses native row slots and the shared action menu",()=>{const html=dashboardTaskRowHtml(tasks[0],false,"Today","today","Alex","Tag",["Home","Cleaning"],["assignee","labels","due"]);assert.doesNotMatch(html,/ha-assist-chip|class="task-content"|class="task-meta"/);assert.match(html,/<ha-list-item-button/);assert.match(html,/<span slot="supporting-text">Alex • Home, Cleaning • <span class="due-date">Today<\/span><\/span>/);assert.match(html,/class="task-icon" slot="start"/);const source=readFileSync(new URL("../../custom_components/tasks/frontend/dashboard-card.js",import.meta.url),"utf8");assert.match(source,/menu\.slot="end";slot\.replaceWith\(menu\)/);assert.doesNotMatch(source,/style=|themeStyles\(\)|this\.styles\(\)/);});
test("dashboard empty state is a native base row",()=>{const html=dashboardCardBodyHtml("",false);assert.match(html,/^<ha-card><ha-list-base aria-label="Tasks"><ha-list-item-base>/);assert.match(html,/mdi:clipboard-check-outline/);const source=readFileSync(new URL("../../custom_components/tasks/frontend/dashboard-card.js",import.meta.url),"utf8");assert.doesNotMatch(source,/style=|themeStyles\(\)|this\.styles\(\)/);});
test("dashboard custom elements are guarded global registrations",()=>{const source=readFileSync(new URL("../../custom_components/tasks/frontend/dashboard-card.js",import.meta.url),"utf8");assert.match(source,/if\(!customElements\.get\("tasks-card"\)\)customElements\.define/);assert.match(source,/if\(!customElements\.get\("tasks-card-editor"\)\)customElements\.define/);assert.doesNotMatch(source,/browser_mod/i);});
test("row menu deletion relies on the shared change event after the mutation",async()=>{const controller=Object.create(TasksBase.prototype),messages=[];controller.confirmAction=async()=>true;controller.ws=async message=>messages.push(message);let loads=0;controller.load=async()=>{loads++;};await controller.deleteTask({task_id:"task",task_name:"Task"});assert.deepEqual(messages,[{type:"tasks/task/delete",task_id:"task"}]);assert.equal(loads,0);});
