services:
  prepare:
    volumes: !override
      - forgejo-workspace:/workspace:ro
      - user-test-config:/config

volumes:
  forgejo-workspace:
    name: ha-tasks-forgejo-workspace
    external: true
