name: Hassfest

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  validate:
    name: Validate integration
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: https://data.forgejo.org/actions/checkout@v4
      - name: Run Hassfest
        uses: https://github.com/home-assistant/actions/hassfest@master
