import { esc, historyNote, locale as activeLocale, setLanguage, t } from "./localize.js";
import { knownLabelIds, withTaskList } from "./sidebar-task-list.js";
import { showTaskViewer } from "./popup-task-viewer.js";
import { withTaskEditor } from "./popup-task-editor.js";
import { withConfirmation } from "./popup-confirm.js";
import { showAttachmentViewer } from "./popup-attachment-viewer.js";
import { showSettingsPopup } from "./popup-settings.js";

export class TasksBase extends withConfirmation(withTaskEditor(withTaskList(HTMLElement))) {
  constructor(){ super(); this.attachShadow({mode:"open"}); this.tasks=[]; this.attachments=[]; this.users=[]; this.tags=[]; this.labels=[]; this.today=""; this.signedFiles=new Map(); this.loading=false; this.reloadPending=false; this.eventUnsubscribe=null; this.eventSubscriptionToken=0; }
  connectedCallback(){this.subscribeEvents();}
  disconnectedCallback(){this.unsubscribeEvents();}
  set hass(value){if(this._hass?.connection!==value?.connection)this.unsubscribeEvents();this._hass=value;this.subscribeEvents();setLanguage(value?.locale?.language).then(changed=>{if(!this.loaded){this.loaded=true;this.load();}else if(changed)this.render();});}
  async subscribeEvents(){if(this.eventUnsubscribe||!this._hass?.connection)return;const token=++this.eventSubscriptionToken,unsubscribe=await this._hass.connection.subscribeEvents(()=>this.load(),"tasks_event");if(token===this.eventSubscriptionToken)this.eventUnsubscribe=unsubscribe;else unsubscribe();}
  unsubscribeEvents(){this.eventSubscriptionToken++;this.eventUnsubscribe?.();this.eventUnsubscribe=null;}
  t(key,variables){return t(key,variables);}
  async ws(msg){ return this._hass.connection.sendMessagePromise(msg); }
  async load(){if(!this._hass)return;if(this.loading){this.reloadPending=true;return;}this.loading=true;try{const [d,tags,labels]=await Promise.all([this.ws({type:"tasks/list"}),this.ws({type:"tag/list"}).catch(()=>[]),this.ws({type:"config/label_registry/list"}).catch(()=>[])]);this.tasks=d.tasks||[];this.attachments=d.attachments||[];this.users=d.users||[];this.tags=Array.isArray(tags)?tags:[];this.labels=Array.isArray(labels)?labels:[];this.today=d.today||"";this.signedFiles.clear();this.render();}catch(err){if(!this.shadowRoot.querySelector(".app"))this.shadowRoot.innerHTML=`<style>:host{display:block;min-height:100%;background:var(--primary-background-color);color:var(--primary-text-color);font-family:var(--ha-font-family-body,Roboto,sans-serif)}main{max-width:880px;margin:auto;padding:12px 8px 36px}</style><div class="app"><main><h1>Tasks</h1><p>${esc(t("panel.load_failed"))}</p></main></div>`;console.error("Tasks load failed",err);}finally{this.loading=false;if(this.reloadPending){this.reloadPending=false;void this.load();}}}
  labelNames(task){const names=new Map(this.labels.map(label=>[label.label_id,label.name]));return knownLabelIds(task?.label_ids,this.labels).map(id=>names.get(id));}
  scheduleText(task){const schedule_interval=Math.max(1,Number(task.schedule_interval)||1),fixed=task.schedule_type==="fixed",schedule_unit=task.schedule_unit||"monthly",periodKey={daily:"day",weekly:"week",monthly:"month",yearly:"year"}[schedule_unit]||"month",singular=t(`schedule.period_${periodKey}`),plural=t(`schedule.period_${periodKey}s`);if(!fixed)return t(schedule_interval===1?"schedule.after_completion_one":"schedule.after_completion_many",{schedule_interval,period:schedule_interval===1?singular:plural});if(schedule_unit==="daily")return t(schedule_interval===1?"schedule.fixed_one":"schedule.fixed_many",{schedule_interval,period:schedule_interval===1?singular:plural});if(schedule_unit==="weekly"){const formatter=new Intl.DateTimeFormat(this.locale(),{weekday:"long",timeZone:"UTC"}),names=Array.from({length:7},(_,index)=>formatter.format(new Date(Date.UTC(2024,0,index+1)))),days=(task.schedule_weekdays||[]).map(day=>names[Number(day)]).filter(Boolean),joined=days.length>1?`${days.slice(0,-1).join(", ")}${t("schedule.and")}${days.at(-1)}`:days[0]||"",when=joined?t("schedule.on_days",{days:joined}):"";return t(schedule_interval===1?"schedule.weekly_one":"schedule.weekly_many",{schedule_interval,days:when});}const day=task.schedule_day==="last"?t("schedule.on_last_day"):t("schedule.on_day_number",{day:Number(task.schedule_day)});if(schedule_unit==="yearly"){const month=new Intl.DateTimeFormat(this.locale(),{month:"long"}).format(new Date(2024,Number(task.schedule_month||1)-1,1)),annualDay=t(task.schedule_day==="last"?"schedule.on_last_day_of_month":"schedule.on_day_of_month",{day:Number(task.schedule_day),month});return t(schedule_interval===1?"schedule.yearly_one":"schedule.yearly_many",{schedule_interval,day:annualDay});}return t(schedule_interval===1?"schedule.monthly_one":"schedule.monthly_many",{schedule_interval,day});}
  editorScheduleHtml(task,dueDates=[],status=""){const rule=esc(this.scheduleText(task).split("\n")[0]),rows=dueDates.map(due=>{const parts=this.dueDateParts(due);return `<div role="row" style="display:contents"><span role="cell">${esc(parts.weekday)}</span><span role="cell">${esc(parts.date)}</span></div>`;}).join("");return `<div>${rule}</div>${rows?`<div role="table" aria-label="${esc(t("task.task_dues"))}" style="display:grid;grid-template-columns:max-content max-content;column-gap:12px;justify-content:start;margin-top:8px">${rows}</div>`:status?`<div style="margin-top:8px">${esc(status)}</div>`:""}`;}
  historyTime(entry){const value=entry.recorded_at?new Date(entry.recorded_at):null;return value&&!Number.isNaN(value.getTime())?value.toLocaleTimeString(this.locale(),{hour:"2-digit",minute:"2-digit"}):"–";}
  historyRow(entry,deletable=false){return `<ha-list-item-base class="history-entry" data-history="${entry.history_entry_id}"><ha-icon slot="start" icon="mdi:history"></ha-icon><span slot="headline">${this.date(entry.completion_date)}, ${this.historyTime(entry)} · ${esc(entry.user_name||t("common.system"))}</span><span slot="supporting-text" title="${esc(t("history.notes"))}">${entry.notes?esc(historyNote(entry.notes)):"–"}</span>${deletable?`<ha-icon-button slot="end" class="editor-action remove danger" label="${esc(t("history.remove"))}" title="${esc(t("common.remove"))}"><ha-icon icon="mdi:delete"></ha-icon></ha-icon-button>`:""}</ha-list-item-base>`;}
  async taskViewer(task){try{await this.ensureTaskFileUrls(task.task_id);}catch{}showTaskViewer(this,task);}
  async deleteTask(task){if(!await this.confirmAction(t("task.delete_title"),t("task.delete_confirm",{name:task.task_name}),t("common.delete"),"danger"))return;await this.ws({type:"tasks/task/delete",task_id:task.task_id});}
  fileLink(file){const name=esc(String(file.filename||"")),url=this.signedFiles.get(file.attachment_id),style="min-width:0;max-width:100%;overflow-wrap:anywhere;text-decoration:none";return url?`<a class="filename file-open" data-file-open="${esc(file.attachment_id)}" href="${esc(url)}" title="${name}" style="${style};min-height:0;padding:0;border:0;background:transparent;text-align:left">${name}</a>`:`<span class="filename" title="${name}" style="${style}">${name}</span>`;}
  openAttachment(file,dispatcher=this){const url=this.signedFiles.get(file.attachment_id);if(url)showAttachmentViewer(dispatcher,file,url);}
  wireFileOpeners(root,dispatcher=this){root.querySelectorAll("[data-file-open]").forEach(link=>{link.onclick=event=>{if(event.composedPath().some(node=>node.classList?.contains("remove")))return;event.preventDefault();event.stopPropagation();const file=this.attachments.find(item=>item.attachment_id===link.dataset.fileOpen);if(file)this.openAttachment(file,dispatcher);};});}
  async ensureTaskFileUrls(taskId){const result=await this.ws({type:"tasks/attachment/urls",task_id:taskId});for(const [id,url] of Object.entries(result.signed_files||{}))this.signedFiles.set(id,url);}
  async uploadNativeFile(file){const data=new FormData();data.append("file",file);const response=await this._hass.fetchWithAuth("/api/file_upload",{method:"POST",body:data});if(response.status===413)throw new Error(this._hass.localize("ui.common.upload_file_too_large",{name:file.name}));if(!response.ok)throw new Error(this._hass.localize("ui.common.unknown_error"));return (await response.json()).file_id;}
  async attachUploadedFile(taskId,fileId){const record=await this.ws({type:"tasks/attachment/create",task_id:taskId,file_id:fileId});if(!this.attachments.some(item=>item.attachment_id===record.attachment_id))this.attachments.push(record);return record;}
  settings(){showSettingsPopup(this);}
  async exportArchive(){const response=await this._hass.fetchWithAuth("/api/tasks/archive");if(!response.ok)throw new Error(await response.text()||String(response.status));const blob=await response.blob(),link=document.createElement("a"),date=new Date().toISOString().slice(0,10);link.href=URL.createObjectURL(blob);link.download=`tasks-${date}.zip`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),0);}
  async importArchive(fileId){await this.ws({type:"tasks/archive/import",file_id:fileId});}
  async discardUploadedFile(fileId){await this._hass.callApi("DELETE","file_upload",{file_id:fileId});}
  locale(){return this._hass?.locale?.language||activeLocale()||navigator.language||"en";}
  date(v){const m=/^(\d{4})-(\d{2})-(\d{2})/.exec(v||"");if(!m)return v;const day=new Date(+m[1],+m[2]-1,+m[3]).toLocaleDateString(this.locale());if(!String(v).includes("T"))return day;const value=new Date(v),time=Number.isNaN(value.getTime())?String(v).slice(11,16):value.toLocaleTimeString(this.locale(),{hour:"2-digit",minute:"2-digit"});return `${day}, ${time}`;}
  dueDateParts(v){const m=/^(\d{4})-(\d{2})-(\d{2})/.exec(v||"");if(!m)return {weekday:"",date:String(v||"")};const value=new Date(+m[1],+m[2]-1,+m[3]),locale=this.locale();return {weekday:value.toLocaleDateString(locale,{weekday:"long"}),date:value.toLocaleDateString(locale,{year:"numeric",month:"2-digit",day:"2-digit"})};}
  dueDate(v){const parts=this.dueDateParts(v);return [parts.weekday,parts.date].filter(Boolean).join(" ");}
  relativeDate(v){const m=/^(\d{4})-(\d{2})-(\d{2})/.exec(v||""),base=/^(\d{4})-(\d{2})-(\d{2})/.exec(this.today||"");if(!m||!base)return v;const target=Date.UTC(+m[1],+m[2]-1,+m[3]),today=Date.UTC(+base[1],+base[2]-1,+base[3]),days=Math.round((target-today)/86400000),absolute=Math.abs(days);let value=days,unit="day";if(absolute>=730){value=Math.round(days/365.2425);unit="year";}else if(absolute>=60){value=Math.round(days/30.4375);unit="month";}else if(absolute>=14){value=Math.round(days/7);unit="week";}const relative=new Intl.RelativeTimeFormat(this.locale(),{numeric:"auto"}).format(value,unit);if(!String(v).includes("T"))return relative;const due=new Date(v),time=Number.isNaN(due.getTime())?String(v).slice(11,16):due.toLocaleTimeString(this.locale(),{hour:"2-digit",minute:"2-digit"});return `${relative}, ${time}`;}
  size(n){return n<1024?`${n} B`:n<1048576?`${Math.round(n/1024)} KB`:`${(n/1048576).toFixed(1)} MB`;}
}

export class TasksPanel extends TasksBase {}
