export const TYPOGRAPHY_STYLES = `<style>.ht-label-medium{color:var(--primary-text-color);font-size:var(--ha-font-size-m,14px);font-weight:var(--ha-font-weight-medium,500)}.ht-label-normal{color:var(--primary-text-color);font-size:var(--ha-font-size-m,14px);font-weight:var(--ha-font-weight-normal,400)}.ht-content{color:var(--secondary-text-color);font-size:var(--ha-font-size-m,14px);font-weight:var(--ha-font-weight-normal,400)}.ht-content-small{color:var(--secondary-text-color);font-size:var(--ha-font-size-s,12px);font-weight:var(--ha-font-weight-normal,400)}</style>`;

export const withStyles = Base => class extends Base {
  typographyStyles(){return TYPOGRAPHY_STYLES;}
  themeStyles(){return `<style>:host{font-family:var(--ha-font-family-body,Roboto,sans-serif);font-size:var(--ha-font-size-m,14px);line-height:var(--ha-line-height-normal,1.4);color:var(--primary-text-color)}</style>`;}
  buttonThemeStyles(){return `<style>.link{color:var(--primary-color);background:transparent}.editor-action.danger{color:var(--error-color);background:transparent}</style>`;}
  formStyles(){return `<style>form,label{display:flex;flex-direction:column;gap:10px}label{gap:4px}.schedule_interval-row{display:flex;gap:10px}.schedule_interval-row>label{flex:1;min-width:0}input,select,textarea{box-sizing:border-box;padding:9px;border:1px solid var(--divider-color);border-radius:8px;background:var(--primary-background-color);color:var(--primary-text-color);font:inherit}textarea{min-height:60px}[data-field="task_description"] textarea{min-height:120px}.error{color:var(--error-color);min-height:16px}.details-content{display:flex;flex-direction:column;gap:10px;padding:0 16px 16px}.detail-row{display:flex;align-items:center;gap:8px;padding:7px 0}.detail-row span,.filename{flex:1}.filename{min-width:0;overflow:hidden;color:var(--primary-color)}.pending{text-decoration:line-through;opacity:.5}.file-list{width:100%}.file-upload-loader[hidden]{display:none}.attachment-upload{display:block;height:240px}button{font:inherit;cursor:pointer;border:0}</style>`;}
  styles(){return `<style>:host{display:block;min-height:100%;background:var(--primary-background-color);color:var(--primary-text-color);font-family:var(--ha-font-family-body,Roboto,sans-serif)}main{max-width:880px;margin:auto;padding:12px 8px 36px}</style>`;}
};
